// This file is auto-generated by @hey-api/openapi-ts

import {
	type Client,
	type ClientMeta,
	formDataBodySerializer,
	type Options as Options2,
	type RequestResult,
	type TDataShape
} from './client';
import { client } from './client.gen';
import type {
	DeleteAssetsByIdData,
	DeleteAssetsByIdErrors,
	DeleteAssetsByIdResponses,
	DeleteRulesByIdData,
	DeleteRulesByIdErrors,
	DeleteRulesByIdResponses,
	GetAssetsByIdData,
	GetAssetsByIdErrors,
	GetAssetsByIdPreviewData,
	GetAssetsByIdPreviewErrors,
	GetAssetsByIdPreviewResponses,
	GetAssetsByIdResponses,
	GetAssetsByIdThumbnailData,
	GetAssetsByIdThumbnailErrors,
	GetAssetsByIdThumbnailResponses,
	GetAssetsData,
	GetAssetsErrors,
	GetAssetsResponses,
	GetRulesByIdData,
	GetRulesByIdErrors,
	GetRulesByIdPreviewData,
	GetRulesByIdPreviewErrors,
	GetRulesByIdPreviewResponses,
	GetRulesByIdResponses,
	GetRulesConditionMetadataData,
	GetRulesConditionMetadataErrors,
	GetRulesConditionMetadataResponses,
	GetRulesData,
	GetRulesErrors,
	GetRulesResponses,
	GetRuntimeActiveData,
	GetRuntimeActiveErrors,
	GetRuntimeActiveResponses,
	GetSettingsData,
	GetSettingsErrors,
	GetSettingsResponses,
	PostAssetsByIdPublishData,
	PostAssetsByIdPublishErrors,
	PostAssetsData,
	PostAssetsErrors,
	PostAssetsResponses,
	PostRulesData,
	PostRulesErrors,
	PostRulesResponses,
	PutAssetsByIdData,
	PutAssetsByIdErrors,
	PutAssetsByIdResponses,
	PutRulesByIdData,
	PutRulesByIdErrors,
	PutRulesByIdResponses,
	PutSettingsData,
	PutSettingsErrors,
	PutSettingsResponses
} from './types.gen';

export type Options<
	TData extends TDataShape = TDataShape,
	ThrowOnError extends boolean = boolean,
	TResponse = unknown
> = Options2<TData, ThrowOnError, TResponse> & {
	/**
	 * You can provide a client instance returned by `createClient()` instead of
	 * individual options. This might be also useful if you want to implement a
	 * custom client.
	 */
	client?: Client;
	/**
	 * You can pass arbitrary values through the `meta` object. This can be
	 * used to access values that aren't defined as part of the SDK function.
	 */
	meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export class V1 {
	public static getAssets<ThrowOnError extends boolean = true>(
		options?: Options<GetAssetsData, ThrowOnError>
	): RequestResult<GetAssetsResponses, GetAssetsErrors, ThrowOnError> {
		return (options?.client ?? client).get<GetAssetsResponses, GetAssetsErrors, ThrowOnError>({
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/umbraco/le-løgin/api/v1/assets',
			...options
		});
	}

	public static postAssets<ThrowOnError extends boolean = true>(
		options: Options<PostAssetsData, ThrowOnError>
	): RequestResult<PostAssetsResponses, PostAssetsErrors, ThrowOnError> {
		return (options.client ?? client).post<PostAssetsResponses, PostAssetsErrors, ThrowOnError>({
			...formDataBodySerializer,
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/umbraco/le-løgin/api/v1/assets',
			...options,
			headers: {
				'Content-Type': null,
				...options.headers
			}
		});
	}

	public static deleteAssetsById<ThrowOnError extends boolean = true>(
		options: Options<DeleteAssetsByIdData, ThrowOnError>
	): RequestResult<DeleteAssetsByIdResponses, DeleteAssetsByIdErrors, ThrowOnError> {
		return (options.client ?? client).delete<
			DeleteAssetsByIdResponses,
			DeleteAssetsByIdErrors,
			ThrowOnError
		>({
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/umbraco/le-løgin/api/v1/assets/{id}',
			...options
		});
	}

	public static getAssetsById<ThrowOnError extends boolean = true>(
		options: Options<GetAssetsByIdData, ThrowOnError>
	): RequestResult<GetAssetsByIdResponses, GetAssetsByIdErrors, ThrowOnError> {
		return (options.client ?? client).get<
			GetAssetsByIdResponses,
			GetAssetsByIdErrors,
			ThrowOnError
		>({
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/umbraco/le-løgin/api/v1/assets/{id}',
			...options
		});
	}

	public static putAssetsById<ThrowOnError extends boolean = true>(
		options: Options<PutAssetsByIdData, ThrowOnError>
	): RequestResult<PutAssetsByIdResponses, PutAssetsByIdErrors, ThrowOnError> {
		return (options.client ?? client).put<
			PutAssetsByIdResponses,
			PutAssetsByIdErrors,
			ThrowOnError
		>({
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/umbraco/le-løgin/api/v1/assets/{id}',
			...options,
			headers: {
				'Content-Type': 'application/json',
				...options.headers
			}
		});
	}

	public static getAssetsByIdPreview<ThrowOnError extends boolean = true>(
		options: Options<GetAssetsByIdPreviewData, ThrowOnError>
	): RequestResult<GetAssetsByIdPreviewResponses, GetAssetsByIdPreviewErrors, ThrowOnError> {
		return (options.client ?? client).get<
			GetAssetsByIdPreviewResponses,
			GetAssetsByIdPreviewErrors,
			ThrowOnError
		>({
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/umbraco/le-løgin/api/v1/assets/{id}/preview',
			...options
		});
	}

	public static postAssetsByIdPublish<ThrowOnError extends boolean = true>(
		options: Options<PostAssetsByIdPublishData, ThrowOnError>
	): RequestResult<unknown, PostAssetsByIdPublishErrors, ThrowOnError> {
		return (options.client ?? client).post<unknown, PostAssetsByIdPublishErrors, ThrowOnError>({
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/umbraco/le-løgin/api/v1/assets/{id}/publish',
			...options
		});
	}

	public static getAssetsByIdThumbnail<ThrowOnError extends boolean = true>(
		options: Options<GetAssetsByIdThumbnailData, ThrowOnError>
	): RequestResult<GetAssetsByIdThumbnailResponses, GetAssetsByIdThumbnailErrors, ThrowOnError> {
		return (options.client ?? client).get<
			GetAssetsByIdThumbnailResponses,
			GetAssetsByIdThumbnailErrors,
			ThrowOnError
		>({
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/umbraco/le-løgin/api/v1/assets/{id}/thumbnail',
			...options
		});
	}

	public static getRules<ThrowOnError extends boolean = true>(
		options?: Options<GetRulesData, ThrowOnError>
	): RequestResult<GetRulesResponses, GetRulesErrors, ThrowOnError> {
		return (options?.client ?? client).get<GetRulesResponses, GetRulesErrors, ThrowOnError>({
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/umbraco/le-løgin/api/v1/rules',
			...options
		});
	}

	public static postRules<ThrowOnError extends boolean = true>(
		options: Options<PostRulesData, ThrowOnError>
	): RequestResult<PostRulesResponses, PostRulesErrors, ThrowOnError> {
		return (options.client ?? client).post<PostRulesResponses, PostRulesErrors, ThrowOnError>({
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/umbraco/le-løgin/api/v1/rules',
			...options,
			headers: {
				'Content-Type': 'application/json',
				...options.headers
			}
		});
	}

	public static deleteRulesById<ThrowOnError extends boolean = true>(
		options: Options<DeleteRulesByIdData, ThrowOnError>
	): RequestResult<DeleteRulesByIdResponses, DeleteRulesByIdErrors, ThrowOnError> {
		return (options.client ?? client).delete<
			DeleteRulesByIdResponses,
			DeleteRulesByIdErrors,
			ThrowOnError
		>({
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/umbraco/le-løgin/api/v1/rules/{id}',
			...options
		});
	}

	public static getRulesById<ThrowOnError extends boolean = true>(
		options: Options<GetRulesByIdData, ThrowOnError>
	): RequestResult<GetRulesByIdResponses, GetRulesByIdErrors, ThrowOnError> {
		return (options.client ?? client).get<GetRulesByIdResponses, GetRulesByIdErrors, ThrowOnError>({
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/umbraco/le-løgin/api/v1/rules/{id}',
			...options
		});
	}

	public static putRulesById<ThrowOnError extends boolean = true>(
		options: Options<PutRulesByIdData, ThrowOnError>
	): RequestResult<PutRulesByIdResponses, PutRulesByIdErrors, ThrowOnError> {
		return (options.client ?? client).put<PutRulesByIdResponses, PutRulesByIdErrors, ThrowOnError>({
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/umbraco/le-løgin/api/v1/rules/{id}',
			...options,
			headers: {
				'Content-Type': 'application/json',
				...options.headers
			}
		});
	}

	public static getRulesByIdPreview<ThrowOnError extends boolean = true>(
		options: Options<GetRulesByIdPreviewData, ThrowOnError>
	): RequestResult<GetRulesByIdPreviewResponses, GetRulesByIdPreviewErrors, ThrowOnError> {
		return (options.client ?? client).get<
			GetRulesByIdPreviewResponses,
			GetRulesByIdPreviewErrors,
			ThrowOnError
		>({
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/umbraco/le-løgin/api/v1/rules/{id}/preview',
			...options
		});
	}

	public static getRulesConditionMetadata<ThrowOnError extends boolean = true>(
		options?: Options<GetRulesConditionMetadataData, ThrowOnError>
	): RequestResult<
		GetRulesConditionMetadataResponses,
		GetRulesConditionMetadataErrors,
		ThrowOnError
	> {
		return (options?.client ?? client).get<
			GetRulesConditionMetadataResponses,
			GetRulesConditionMetadataErrors,
			ThrowOnError
		>({
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/umbraco/le-løgin/api/v1/rules/condition-metadata',
			...options
		});
	}

	public static getRuntimeActive<ThrowOnError extends boolean = true>(
		options?: Options<GetRuntimeActiveData, ThrowOnError>
	): RequestResult<GetRuntimeActiveResponses, GetRuntimeActiveErrors, ThrowOnError> {
		return (options?.client ?? client).get<
			GetRuntimeActiveResponses,
			GetRuntimeActiveErrors,
			ThrowOnError
		>({
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/umbraco/le-løgin/api/v1/runtime/active',
			...options
		});
	}

	public static getSettings<ThrowOnError extends boolean = true>(
		options?: Options<GetSettingsData, ThrowOnError>
	): RequestResult<GetSettingsResponses, GetSettingsErrors, ThrowOnError> {
		return (options?.client ?? client).get<GetSettingsResponses, GetSettingsErrors, ThrowOnError>({
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/umbraco/le-løgin/api/v1/settings',
			...options
		});
	}

	public static putSettings<ThrowOnError extends boolean = true>(
		options: Options<PutSettingsData, ThrowOnError>
	): RequestResult<PutSettingsResponses, PutSettingsErrors, ThrowOnError> {
		return (options.client ?? client).put<PutSettingsResponses, PutSettingsErrors, ThrowOnError>({
			security: [{ scheme: 'bearer', type: 'http' }],
			url: '/umbraco/le-løgin/api/v1/settings',
			...options,
			headers: {
				'Content-Type': 'application/json',
				...options.headers
			}
		});
	}
}
