// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://localhost:5001' | (string & {});
};

export type ActiveLeLøginScreenResponse = {
    assetId: string;
    imageUrl: string;
    altText?: string | null;
    greetingText?: string | null;
    focalPoint?: FocalPoint | null;
    zoom?: number | null;
    logoAssetId?: string | null;
};

export type AssetUpdateRequest = {
    name?: string | null;
    altText?: string | null;
    greetingText?: string | null;
    logoAssetId?: string | null;
    focalPoint?: FocalPoint | null;
    zoom?: number | null;
};

export type ConditionFieldMetadata = {
    operators: Array<string>;
    defaultValue: unknown;
    allowedValues?: Array<unknown> | null;
};

export type ConditionMetadataResponse = {
    operators: {
        [key: string]: ConditionOperatorMetadata;
    };
    fields: {
        [key: string]: ConditionFieldMetadata;
    };
};

export type ConditionOperatorMetadata = {
    arity: string;
};

export type FocalPoint = {
    left: number;
    top: number;
};

export type LoginImageAsset = {
    id: string;
    name: string;
    kind: 'Background' | 'Logo';
    altText?: string | null;
    greetingText?: string | null;
    logoAssetId?: string | null;
    storagePath: string;
    publicPath?: string | null;
    width: number;
    height: number;
    focalPoint?: FocalPoint | null;
    zoom: number;
    createdAt: string;
    updatedAt: string;
};

export type LoginRuleConditionGroupModel = {
    operator: 'All' | 'Any';
    conditions: Array<LoginRuleConditionModel>;
};

export type LoginRuleConditionModel = {
    id: string;
    field: 'Weekday' | 'Month' | 'Date' | 'Hostname';
    operator: 'Is' | 'IsNot' | 'In' | 'NotIn' | 'Between' | 'NotBetween';
    values: Array<string | number>;
};

export type LoginRuleResponseModel = {
    id: string;
    name: string;
    priority: number;
    enabled: boolean;
    condition: LoginRuleConditionGroupModel;
    assetIds: Array<string>;
};

export type LoginSettings = {
    publicEndpointCacheSeconds: number;
};

export type SaveRuleRequest = {
    id?: string | null;
    name: string;
    priority: number;
    enabled: boolean;
    condition: LoginRuleConditionGroupModel;
    assetIds: Array<string>;
};

export type GetUmbracoLeLøginApiV1AssetsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/le-løgin/api/v1/assets';
};

export type GetUmbracoLeLøginApiV1AssetsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetUmbracoLeLøginApiV1AssetsResponses = {
    /**
     * OK
     */
    200: Array<LoginImageAsset>;
};

export type GetUmbracoLeLøginApiV1AssetsResponse = GetUmbracoLeLøginApiV1AssetsResponses[keyof GetUmbracoLeLøginApiV1AssetsResponses];

export type PostUmbracoLeLøginApiV1AssetsData = {
    body?: {
        file: Blob | File;
        name: string;
        kind: 'Background' | 'Logo';
        altText?: string;
    };
    path?: never;
    query?: never;
    url: '/umbraco/le-løgin/api/v1/assets';
};

export type PostUmbracoLeLøginApiV1AssetsErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PostUmbracoLeLøginApiV1AssetsResponses = {
    /**
     * Created
     */
    201: LoginImageAsset;
};

export type PostUmbracoLeLøginApiV1AssetsResponse = PostUmbracoLeLøginApiV1AssetsResponses[keyof PostUmbracoLeLøginApiV1AssetsResponses];

export type DeleteUmbracoLeLøginApiV1AssetsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/le-løgin/api/v1/assets/{id}';
};

export type DeleteUmbracoLeLøginApiV1AssetsByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type DeleteUmbracoLeLøginApiV1AssetsByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteUmbracoLeLøginApiV1AssetsByIdResponse = DeleteUmbracoLeLøginApiV1AssetsByIdResponses[keyof DeleteUmbracoLeLøginApiV1AssetsByIdResponses];

export type GetUmbracoLeLøginApiV1AssetsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/le-løgin/api/v1/assets/{id}';
};

export type GetUmbracoLeLøginApiV1AssetsByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetUmbracoLeLøginApiV1AssetsByIdResponses = {
    /**
     * OK
     */
    200: LoginImageAsset;
};

export type GetUmbracoLeLøginApiV1AssetsByIdResponse = GetUmbracoLeLøginApiV1AssetsByIdResponses[keyof GetUmbracoLeLøginApiV1AssetsByIdResponses];

export type PutUmbracoLeLøginApiV1AssetsByIdData = {
    body?: AssetUpdateRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/le-løgin/api/v1/assets/{id}';
};

export type PutUmbracoLeLøginApiV1AssetsByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type PutUmbracoLeLøginApiV1AssetsByIdResponses = {
    /**
     * OK
     */
    200: LoginImageAsset;
};

export type PutUmbracoLeLøginApiV1AssetsByIdResponse = PutUmbracoLeLøginApiV1AssetsByIdResponses[keyof PutUmbracoLeLøginApiV1AssetsByIdResponses];

export type GetUmbracoLeLøginApiV1AssetsByIdPreviewData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/le-løgin/api/v1/assets/{id}/preview';
};

export type GetUmbracoLeLøginApiV1AssetsByIdPreviewErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetUmbracoLeLøginApiV1AssetsByIdPreviewResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type PostUmbracoLeLøginApiV1AssetsByIdPublishData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/le-løgin/api/v1/assets/{id}/publish';
};

export type PostUmbracoLeLøginApiV1AssetsByIdPublishErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetUmbracoLeLøginApiV1AssetsByIdThumbnailData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/le-løgin/api/v1/assets/{id}/thumbnail';
};

export type GetUmbracoLeLøginApiV1AssetsByIdThumbnailErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetUmbracoLeLøginApiV1AssetsByIdThumbnailResponses = {
    /**
     * OK
     */
    200: unknown;
};

export type GetUmbracoLeLøginApiV1RulesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/le-løgin/api/v1/rules';
};

export type GetUmbracoLeLøginApiV1RulesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetUmbracoLeLøginApiV1RulesResponses = {
    /**
     * OK
     */
    200: Array<LoginRuleResponseModel>;
};

export type GetUmbracoLeLøginApiV1RulesResponse = GetUmbracoLeLøginApiV1RulesResponses[keyof GetUmbracoLeLøginApiV1RulesResponses];

export type PostUmbracoLeLøginApiV1RulesData = {
    body?: SaveRuleRequest;
    path?: never;
    query?: never;
    url: '/umbraco/le-løgin/api/v1/rules';
};

export type PostUmbracoLeLøginApiV1RulesErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PostUmbracoLeLøginApiV1RulesResponses = {
    /**
     * Created
     */
    201: LoginRuleResponseModel;
};

export type PostUmbracoLeLøginApiV1RulesResponse = PostUmbracoLeLøginApiV1RulesResponses[keyof PostUmbracoLeLøginApiV1RulesResponses];

export type DeleteUmbracoLeLøginApiV1RulesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/le-løgin/api/v1/rules/{id}';
};

export type DeleteUmbracoLeLøginApiV1RulesByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type DeleteUmbracoLeLøginApiV1RulesByIdResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteUmbracoLeLøginApiV1RulesByIdResponse = DeleteUmbracoLeLøginApiV1RulesByIdResponses[keyof DeleteUmbracoLeLøginApiV1RulesByIdResponses];

export type GetUmbracoLeLøginApiV1RulesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/le-løgin/api/v1/rules/{id}';
};

export type GetUmbracoLeLøginApiV1RulesByIdErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetUmbracoLeLøginApiV1RulesByIdResponses = {
    /**
     * OK
     */
    200: LoginRuleResponseModel;
};

export type GetUmbracoLeLøginApiV1RulesByIdResponse = GetUmbracoLeLøginApiV1RulesByIdResponses[keyof GetUmbracoLeLøginApiV1RulesByIdResponses];

export type PutUmbracoLeLøginApiV1RulesByIdData = {
    body?: SaveRuleRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/le-løgin/api/v1/rules/{id}';
};

export type PutUmbracoLeLøginApiV1RulesByIdErrors = {
    /**
     * Bad Request
     */
    400: unknown;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type PutUmbracoLeLøginApiV1RulesByIdResponses = {
    /**
     * OK
     */
    200: LoginRuleResponseModel;
};

export type PutUmbracoLeLøginApiV1RulesByIdResponse = PutUmbracoLeLøginApiV1RulesByIdResponses[keyof PutUmbracoLeLøginApiV1RulesByIdResponses];

export type GetUmbracoLeLøginApiV1RulesByIdPreviewData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/umbraco/le-løgin/api/v1/rules/{id}/preview';
};

export type GetUmbracoLeLøginApiV1RulesByIdPreviewErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * Not Found
     */
    404: unknown;
};

export type GetUmbracoLeLøginApiV1RulesByIdPreviewResponses = {
    /**
     * OK
     */
    200: ActiveLeLøginScreenResponse;
    /**
     * No Content
     */
    204: void;
};

export type GetUmbracoLeLøginApiV1RulesByIdPreviewResponse = GetUmbracoLeLøginApiV1RulesByIdPreviewResponses[keyof GetUmbracoLeLøginApiV1RulesByIdPreviewResponses];

export type GetUmbracoLeLøginApiV1RulesConditionMetadataData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/le-løgin/api/v1/rules/condition-metadata';
};

export type GetUmbracoLeLøginApiV1RulesConditionMetadataErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetUmbracoLeLøginApiV1RulesConditionMetadataResponses = {
    /**
     * OK
     */
    200: ConditionMetadataResponse;
};

export type GetUmbracoLeLøginApiV1RulesConditionMetadataResponse = GetUmbracoLeLøginApiV1RulesConditionMetadataResponses[keyof GetUmbracoLeLøginApiV1RulesConditionMetadataResponses];

export type GetUmbracoLeLøginApiV1RuntimeActiveData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/le-løgin/api/v1/runtime/active';
};

export type GetUmbracoLeLøginApiV1RuntimeActiveErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetUmbracoLeLøginApiV1RuntimeActiveResponses = {
    /**
     * OK
     */
    200: ActiveLeLøginScreenResponse;
    /**
     * No Content
     */
    204: void;
};

export type GetUmbracoLeLøginApiV1RuntimeActiveResponse = GetUmbracoLeLøginApiV1RuntimeActiveResponses[keyof GetUmbracoLeLøginApiV1RuntimeActiveResponses];

export type GetUmbracoLeLøginApiV1SettingsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/le-løgin/api/v1/settings';
};

export type GetUmbracoLeLøginApiV1SettingsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetUmbracoLeLøginApiV1SettingsResponses = {
    /**
     * OK
     */
    200: LoginSettings;
};

export type GetUmbracoLeLøginApiV1SettingsResponse = GetUmbracoLeLøginApiV1SettingsResponses[keyof GetUmbracoLeLøginApiV1SettingsResponses];

export type PutUmbracoLeLøginApiV1SettingsData = {
    body?: LoginSettings;
    path?: never;
    query?: never;
    url: '/umbraco/le-løgin/api/v1/settings';
};

export type PutUmbracoLeLøginApiV1SettingsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PutUmbracoLeLøginApiV1SettingsResponses = {
    /**
     * OK
     */
    200: LoginSettings;
};

export type PutUmbracoLeLøginApiV1SettingsResponse = PutUmbracoLeLøginApiV1SettingsResponses[keyof PutUmbracoLeLøginApiV1SettingsResponses];
