// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
	baseUrl: 'http://localhost:5099/' | (string & {});
};

export type ActiveLeLøginScreenResponse = {
	assetId: string;
	imageUrl: string;
	altText: null | string;
	greetingText: null | string;
	focalPoint: null | FocalPoint;
	zoom: null | number | string;
	logoAssetId: null | string;
};

export type AssetUpdateRequest = {
	name: null | string;
	altText: null | string;
	greetingText: null | string;
	logoAssetId: null | string;
	focalPoint: null | FocalPoint;
	zoom: null | number | string;
};

export type ConditionFieldMetadata = {
	operators: Array<string>;
	defaultValue: unknown;
	allowedValues?: null | Array<unknown>;
};

export type ConditionMetadataResponse = {
	operators: {
		[key: string]: ConditionOperatorMetadata;
	};
	fields: {
		[key: string]: ConditionFieldMetadata;
	};
};

export type ConditionOperatorMetadata = {
	arity: string;
};

export type FocalPoint = {
	left: number | string;
	top: number | string;
};

export type IFormFile = Blob | File;

export type LoginImageAsset = {
	id: string;
	name: string;
	kind: LoginImageAssetKind;
	altText?: null | string;
	greetingText?: null | string;
	logoAssetId?: null | string;
	storagePath: string;
	publicPath?: null | string;
	width: number | string;
	height: number | string;
	focalPoint?: null | FocalPoint;
	zoom: number | string;
	createdAt: string;
	updatedAt: string;
};

export type LoginImageAssetKind = 'background' | 'logo';

export type LoginRuleConditionGroupModel = {
	operator: LoginRuleConditionGroupOperator;
	conditions: Array<LoginRuleConditionModel>;
};

export type LoginRuleConditionGroupOperator = 'all' | 'any';

export type LoginRuleConditionModel = {
	id: string;
	field: LoginRuleField;
	operator: LoginRuleConditionOperator;
	values: Array<string | number>;
};

export type LoginRuleConditionOperator = 'is' | 'isNot' | 'in' | 'notIn' | 'between' | 'notBetween';

export type LoginRuleField = 'weekday' | 'month';

export type LoginRuleResponseModel = {
	id: string;
	name: string;
	priority: number | string;
	enabled: boolean;
	condition: LoginRuleConditionGroupModel;
	assetIds: Array<string>;
};

export type LoginSettings = {
	publicEndpointCacheSeconds: number | string;
};

export type SaveRuleRequest = {
	id?: null | string;
	name: string;
	priority: number | string;
	enabled: boolean;
	condition: LoginRuleConditionGroupModel;
	assetIds: Array<string>;
};

export type GetAssetsData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/umbraco/le-løgin/api/v1/assets';
};

export type GetAssetsErrors = {
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
};

export type GetAssetsResponses = {
	/**
	 * OK
	 */
	200: Array<LoginImageAsset>;
};

export type GetAssetsResponse = GetAssetsResponses[keyof GetAssetsResponses];

export type PostAssetsData = {
	body: {
		file?: IFormFile;
		name?: string;
		kind?: LoginImageAssetKind;
		altText?: string;
	};
	path?: never;
	query?: never;
	url: '/umbraco/le-løgin/api/v1/assets';
};

export type PostAssetsErrors = {
	/**
	 * Bad Request
	 */
	400: unknown;
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
};

export type PostAssetsResponses = {
	/**
	 * Created
	 */
	201: LoginImageAsset;
};

export type PostAssetsResponse = PostAssetsResponses[keyof PostAssetsResponses];

export type DeleteAssetsByIdData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: '/umbraco/le-løgin/api/v1/assets/{id}';
};

export type DeleteAssetsByIdErrors = {
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
	/**
	 * Not Found
	 */
	404: unknown;
};

export type DeleteAssetsByIdResponses = {
	/**
	 * No Content
	 */
	204: unknown;
};

export type GetAssetsByIdData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: '/umbraco/le-løgin/api/v1/assets/{id}';
};

export type GetAssetsByIdErrors = {
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
	/**
	 * Not Found
	 */
	404: unknown;
};

export type GetAssetsByIdResponses = {
	/**
	 * OK
	 */
	200: LoginImageAsset;
};

export type GetAssetsByIdResponse = GetAssetsByIdResponses[keyof GetAssetsByIdResponses];

export type PutAssetsByIdData = {
	body: AssetUpdateRequest;
	path: {
		id: string;
	};
	query?: never;
	url: '/umbraco/le-løgin/api/v1/assets/{id}';
};

export type PutAssetsByIdErrors = {
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
	/**
	 * Not Found
	 */
	404: unknown;
};

export type PutAssetsByIdResponses = {
	/**
	 * OK
	 */
	200: LoginImageAsset;
};

export type PutAssetsByIdResponse = PutAssetsByIdResponses[keyof PutAssetsByIdResponses];

export type GetAssetsByIdPreviewData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: '/umbraco/le-løgin/api/v1/assets/{id}/preview';
};

export type GetAssetsByIdPreviewErrors = {
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
	/**
	 * Not Found
	 */
	404: unknown;
};

export type GetAssetsByIdPreviewResponses = {
	/**
	 * OK
	 */
	200: unknown;
};

export type PostAssetsByIdPublishData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: '/umbraco/le-løgin/api/v1/assets/{id}/publish';
};

export type PostAssetsByIdPublishErrors = {
	/**
	 * Bad Request
	 */
	400: unknown;
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
	/**
	 * Not Found
	 */
	404: unknown;
};

export type GetAssetsByIdThumbnailData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: '/umbraco/le-løgin/api/v1/assets/{id}/thumbnail';
};

export type GetAssetsByIdThumbnailErrors = {
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
	/**
	 * Not Found
	 */
	404: unknown;
};

export type GetAssetsByIdThumbnailResponses = {
	/**
	 * OK
	 */
	200: unknown;
};

export type GetRulesData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/umbraco/le-løgin/api/v1/rules';
};

export type GetRulesErrors = {
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
};

export type GetRulesResponses = {
	/**
	 * OK
	 */
	200: Array<LoginRuleResponseModel>;
};

export type GetRulesResponse = GetRulesResponses[keyof GetRulesResponses];

export type PostRulesData = {
	body: SaveRuleRequest;
	path?: never;
	query?: never;
	url: '/umbraco/le-løgin/api/v1/rules';
};

export type PostRulesErrors = {
	/**
	 * Bad Request
	 */
	400: unknown;
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
};

export type PostRulesResponses = {
	/**
	 * Created
	 */
	201: LoginRuleResponseModel;
};

export type PostRulesResponse = PostRulesResponses[keyof PostRulesResponses];

export type DeleteRulesByIdData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: '/umbraco/le-løgin/api/v1/rules/{id}';
};

export type DeleteRulesByIdErrors = {
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
	/**
	 * Not Found
	 */
	404: unknown;
};

export type DeleteRulesByIdResponses = {
	/**
	 * No Content
	 */
	204: unknown;
};

export type GetRulesByIdData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: '/umbraco/le-løgin/api/v1/rules/{id}';
};

export type GetRulesByIdErrors = {
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
	/**
	 * Not Found
	 */
	404: unknown;
};

export type GetRulesByIdResponses = {
	/**
	 * OK
	 */
	200: LoginRuleResponseModel;
};

export type GetRulesByIdResponse = GetRulesByIdResponses[keyof GetRulesByIdResponses];

export type PutRulesByIdData = {
	body: SaveRuleRequest;
	path: {
		id: string;
	};
	query?: never;
	url: '/umbraco/le-løgin/api/v1/rules/{id}';
};

export type PutRulesByIdErrors = {
	/**
	 * Bad Request
	 */
	400: unknown;
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
	/**
	 * Not Found
	 */
	404: unknown;
};

export type PutRulesByIdResponses = {
	/**
	 * OK
	 */
	200: LoginRuleResponseModel;
};

export type PutRulesByIdResponse = PutRulesByIdResponses[keyof PutRulesByIdResponses];

export type GetRulesByIdPreviewData = {
	body?: never;
	path: {
		id: string;
	};
	query?: never;
	url: '/umbraco/le-løgin/api/v1/rules/{id}/preview';
};

export type GetRulesByIdPreviewErrors = {
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
	/**
	 * Not Found
	 */
	404: unknown;
};

export type GetRulesByIdPreviewResponses = {
	/**
	 * OK
	 */
	200: ActiveLeLøginScreenResponse;
	/**
	 * No Content
	 */
	204: unknown;
};

export type GetRulesByIdPreviewResponse =
	GetRulesByIdPreviewResponses[keyof GetRulesByIdPreviewResponses];

export type GetRulesConditionMetadataData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/umbraco/le-løgin/api/v1/rules/condition-metadata';
};

export type GetRulesConditionMetadataErrors = {
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
};

export type GetRulesConditionMetadataResponses = {
	/**
	 * OK
	 */
	200: ConditionMetadataResponse;
};

export type GetRulesConditionMetadataResponse =
	GetRulesConditionMetadataResponses[keyof GetRulesConditionMetadataResponses];

export type GetRuntimeActiveData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/umbraco/le-løgin/api/v1/runtime/active';
};

export type GetRuntimeActiveErrors = {
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
};

export type GetRuntimeActiveResponses = {
	/**
	 * OK
	 */
	200: ActiveLeLøginScreenResponse;
	/**
	 * No Content
	 */
	204: unknown;
};

export type GetRuntimeActiveResponse = GetRuntimeActiveResponses[keyof GetRuntimeActiveResponses];

export type GetSettingsData = {
	body?: never;
	path?: never;
	query?: never;
	url: '/umbraco/le-løgin/api/v1/settings';
};

export type GetSettingsErrors = {
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
};

export type GetSettingsResponses = {
	/**
	 * OK
	 */
	200: LoginSettings;
};

export type GetSettingsResponse = GetSettingsResponses[keyof GetSettingsResponses];

export type PutSettingsData = {
	body: LoginSettings;
	path?: never;
	query?: never;
	url: '/umbraco/le-løgin/api/v1/settings';
};

export type PutSettingsErrors = {
	/**
	 * The resource is protected and requires an authentication token
	 */
	401: unknown;
};

export type PutSettingsResponses = {
	/**
	 * OK
	 */
	200: LoginSettings;
};

export type PutSettingsResponse = PutSettingsResponses[keyof PutSettingsResponses];
